### PR TITLE
add: Basic md files for the repo

### PR DESCRIPTION
**Pull request by Sonakshi1901**

### CODE REVIEW

**Comment by Sonakshi1901** [comment]
After Padmaja finishes the Gatsby configuration, I will install eslint and create the required files for it.

**Comment by Sonakshi1901** [comment]
Once Padmaja's PR is merged, I will add the ESLint files

**Comment by Sonakshi1901** [comment]
If you want any changes in the README file, do let me know; I will send it in the next PR.

**Comment by riteshsp2000** [comment]
> Once Padmaja's PR is merged, I will add the ESLint files. If you want any changes in the README file, do let me know; I will send it in the next PR.

Hey @Sonakshi1901 Padmaja's PR is merged

**Pull request closed without merging**
